[functions.asaas-create-checkout]
verify_jwt = true

[functions.asaas-webhook]
verify_jwt = false

[functions.asaas-cancel-subscription]
verify_jwt = true

[functions.auth-send-email-onesignal]
verify_jwt = false
