[functions.asaas-create-checkout]
verify_jwt = true

[functions.asaas-webhook]
verify_jwt = false

[functions.asaas-cancel-subscription]
verify_jwt = true

[functions.auth-email]
verify_jwt = false

[functions.asaas-cancel-downgrade]
verify_jwt = true

[functions.process-billing-events]
verify_jwt = false
